config/routes.rb
Rails.application.routes.draw do
  resources :facts

  root 'welcome#index'
  get "/facts", to: "facts#index"
  get "/facts/:id", to: "facts#show"
  get "/facts/new", to: "facts#new"
  post "/facts", to: "facts#create"  # usually a submitted form
  get "/facts/:id/edit", to: "facts#edit"
  patch "/facts/:id", to: "facts#update" # usually a submitted form
  delete "/facts/:id", to: "facts#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
  validates :category, presence: true,
            length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
##  http_basic_authenticate_with name: "dhh", password: "secret", except:
##  [:index, :show]

  def index
    @facts = Fact.all
  end

  def show
    @fact= Fact.find(params[:id])
  end

  def new
    @fact= Fact.new
  end

  def edit
    @fact= Fact.find(params[:id])
  end

  def create
    @fact= Fact.new(fact_params)

    if @fact.save
      redirect_to @fact
    else
      render 'new'
    end
  end

  def update
    @fact= Fact.find(params[:id])

    if @fact.update(fact_params)
      redirect_to @fact
    else
      render 'edit'
    end
  end

  def destroy
    @fact= Fact.find(params[:id])
    @fact.destroy

    redirect_to facts_path
  end

  private
    def fact_params
      params.require(:fact).permit(:category, :body, :source)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/facts/_form.html.erb
<div id="formMain">
	<%= form_for @fact do |f|%>
		<% if @fact.errors.any? %>
		 <div id="error_explanation">
			 <h2>
				 <%= pluralize(@fact.errors.count, "error") %> prohibited
				 this fact from being saved:
			 </h2>
			 <ul>
				 <% @fact.errors.full_messages.each do |msg| %>
					 <li><%= msg %></li>
				 <% end %>
			 </ul>
		 </div>
		<% end %>

		<div class="container"><br/>
				<div class="column-right">
					<%= f.label :category %>:<br/><br/>
					<%= f.label :text %>:<br/><br/>
					<%= f.label :source %>:<br/><br/>
				</div>
				<div class="column-left">
					<%= f.text_field :category %><br/><br/>
					<%= f.text_field :body%><br/><br/>
					<%= f.text_field :source %><br/><br/>
			</div>
		</div>
		<button class="buttonStyle">
			<%= f.submit %>
			<%= link_to 'Back', facts_path, class: 'buttonStyle'%>
		</button>
	<% end %>
</div>

app/views/facts/edit.html.erb
  <br/>
  <center>
    <h5>Edit Fact</h5></center>
    <div id='new'>
      <%= render 'form' %>
    </div>
  <br/>

app/views/facts/index.html.erb
<br/><br/><center>
<h1 style="background:none; color:#461968"><b>FACTS</b></h1>

<table style="width:80%;">
  <tr style="font-size:48px; color:white; background-color:black;">
    <th style="width:33%;">Category</th>
    <th style="width:33%;">Body</th>
    <th style="width:33%;">Source</th>
  </tr>
<div style="background-color:white;">
  <% @facts.each do |fact| %>
  <tr style="background-color:white;">
    <td style="font-size:40px; padding-left:15px;"><%= fact.category %></td>
    <td style="font-size:40px; padding-left:15px;"><%= fact.body %></td>
    <td style="font-size:22px;">&#160;&#160;
      <%= link_to 'Show', fact_path(fact) %>&#160;&#160;
      <%= link_to 'Edit', edit_fact_path(fact) %>&#160;&#160;
      <%= link_to 'Delete', fact_path(fact), method: :delete, data: { confirm: 'Delete this fact?' } %>
    </td>
  </tr>
  <% end %>
</table></center><br/><br/><br/>

<%= link_to 'New Fact', new_fact_path, :class => 'buttonStyle' %>

app/views/facts/new.html.erb
  <br/>
  <center>
    <h5>New Fact</h5></center>
    <div id='new'>
      <%= render 'form' %>
    </div>
  <br/>

app/views/facts/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @fact.category %>
</p>
<p>
  <strong>Body:</strong>
  <%= @fact.body %>
</p>
<p>
  <strong>Source:</strong>
  <%= @fact.source %>
</p><br/><br/>
<%= link_to 'Edit', edit_fact_path(@fact),:class => 'buttonStyle'  %>
<%= link_to 'Back', facts_path, :class => 'buttonStyle'  %>

app/views/layouts/application.html.erb
<DOCTYPE html>
  <head>
    <title>RaleighNewcomer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <img src='http://i.imgur.com/cdc15lz.png' style='position:fixed;top:0px;left:0px; width:103%; height:100%; position:cover; z-index:-1; margin-left:-1.5%; margin-right:-1.5%;'>
  </head>

  <body>
    <%= yield %>
  </body>
  </html>

app/views/welcome/index.html.erb
<DOCTYPE html>
  <head>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
    <title> Raleigh Newcomer</title><br/><br/><br/>
    <!-- <img src='http://i.imgur.com/zBTl5Fu.png' style='position:fixed;top:0px;left:0px;width:105%;height:100%;z-index:-1; margin-left:-1.5%; margin-right:-1.5%;'> -->
  </head>
  <body>
      <div id="main_div">
        <center>
        <h1>RALEIGH NEWCOMER<br/><br/>
        <%= link_to 'Raleigh Stuff - Enjoy!',controller: 'facts' %></h1><br/><br/>
        <% yield %>
        <p>I've been fortunate enough to see some beautiful cities - Munich, London, Paris -- I've also lived all around the
        beautiful DC area. (Baltimore City, 5 minutes outside of Crystal City, Northern VA, Manassas.) When I hit 26, I finally
        decided to find a nice quiet place to settle down. I essentially picked Raleigh off a map, and I've loved it ever since.
        Since this is a smaller city than I'm used to, I am making this app to catalog the good places I've found down here.
        (Especially since there are certain things - like good sushi - that are like LochNess level hard to find :/)</p>
      </div>
    </center>
   </body>
   </html>